name: Publish description

on:
  workflow_dispatch:
    inputs:
      comment:
        description: "comment"
        required: true


jobs:
  publish_doc:
    name: Publish doc

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v2

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: anasoid/jmeter
