name: Publish description to docker hub ⚓

on:
  workflow_dispatch:
    inputs:
      comment:
        description: "comment"
        required: true
        default: "TODO"

jobs:
  publish_doc:
    name: Build, Test and Publish

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v2

      #Publish on master
      - name: Login to DockerHub 📦
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORDs }}
          repository: anasoid/jmeter
