name: Publish description

on:
  workflow_dispatch:
    inputs:
      comment:
        description: "comment"
        required: true


jobs:
  publish_doc:
    name: Publish doc

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ✅
        uses: actions/checkout@v2

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASSWORD }}
        with:
          destination_container_repo: anasoid/jmeter
          provider: dockerhub
          short_description: 'Docker Jmeter'
          readme_file: 'README.md'